version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./staticfiles:/app/static
      - ./mediafiles:/app/mediafiles
    command: 'sh -c "python3 manage.py migrate && python3 manage.py collectstatic --noinput && gunicorn -c ./configs/configs.py core.wsgi"'
    restart: always
    ports:
      - '8034:8034'
