# Generated by Django 5.2 on 2025-04-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
