# Generated by Django 5.2 on 2025-04-24 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_matricula'),
        ('reciclagem', '0005_cidade_estado_tiporesiduos_remove_reciclagem_turno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='reciclagem.turma'),
        ),
    ]
