# Generated by Django 5.2 on 2025-04-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_turma'),
        ('reciclagem', '0007_alter_curso_unidade_alter_reciclagem_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='reciclagem.turma'),
        ),
    ]
