# Generated by Django 4.2.16 on 2025-02-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
