# Generated by Django 4.2.16 on 2025-04-24 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Resíduo',
                'verbose_name_plural': 'Tipos de Resíduos',
            },
        ),
        migrations.CreateModel(
            name='Reciclagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20)),
                ('turma', models.CharField(max_length=20)),
                ('turno', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('noturno', 'Noturno')], max_length=20)),
                ('semestre', models.CharField(max_length=10)),
                ('unidade', models.CharField(choices=[('alcindo_cancela', 'Unama Alcindo Cancela'), ('ananindeua', 'Unama Ananindeua'), ('outro', 'Outro')], max_length=50)),
                ('quantidade', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_residuo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reciclagem.tiporesiduo', verbose_name='Tipo de Residuo')),
            ],
        ),
    ]
