# Generated by Django 4.2.16 on 2025-04-24 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciclagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('noturno', 'Noturno')], help_text='Código interno do turno', max_length=20, unique=True)),
                ('nome', models.CharField(help_text='Descrição amigável do turno', max_length=20)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('alcindo_cancela', 'Unama Alcindo Cancela'), ('ananindeua', 'Unama Ananindeua'), ('outro', 'Outro')], help_text='Código interno da unidade', max_length=50, unique=True)),
                ('nome', models.CharField(help_text='Nome completo da unidade', max_length=100)),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.AlterField(
            model_name='reciclagem',
            name='tipo_residuo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reciclagem.tiporesiduo', verbose_name='Tipo de Resíduo'),
        ),
        migrations.AlterField(
            model_name='reciclagem',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reciclagem.turno', verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='reciclagem',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reciclagem.unidade', verbose_name='Unidade'),
        ),
    ]
