# Generated by Django 4.2.16 on 2025-04-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclagem', '0002_turno_unidade_alter_reciclagem_tipo_residuo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='code',
            field=models.CharField(choices=[('alcindo_cancela', 'Unama Alcindo Cancela'), ('ananindeua', 'Unama Ananindeua'), ('outro', 'Outro')], default='alcindo_cancela', help_text='Código interno da unidade', max_length=50, unique=True),
        ),
    ]
