# Generated by Django 4.2.16 on 2025-04-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclagem', '0003_alter_unidade_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporesiduo',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
