# Generated by Django 5.2 on 2025-04-24 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclagem', '0004_alter_tiporesiduo_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='TipoResiduos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Resíduo',
                'verbose_name_plural': 'Tipos de Resíduos',
            },
        ),
        migrations.RemoveField(
            model_name='reciclagem',
            name='turno',
        ),
        migrations.AlterModelOptions(
            name='reciclagem',
            options={'verbose_name': 'Reciclagem', 'verbose_name_plural': 'Reciclagens'},
        ),
        migrations.RemoveField(
            model_name='reciclagem',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='reciclagem',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='reciclagem',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='reciclagem',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='reciclagem',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='reciclagem',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='reciclagem',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='code',
        ),
        migrations.AddField(
            model_name='reciclagem',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciclagens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reciclagem',
            name='data',
            field=models.DateField(auto_now_add=True, default='2025-04-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidade',
            name='endereco',
            field=models.CharField(default='teste', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reciclagem',
            name='quantidade',
            field=models.FloatField(help_text='Quantidade em kg'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='reciclagem.cidade'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('duracao', models.IntegerField(help_text='Duração em Semestres')),
                ('coordenador', models.CharField(help_text='Nome do Coordenador', max_length=100)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='reciclagem.unidade')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.AddField(
            model_name='unidade',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='reciclagem.estado'),
        ),
        migrations.AlterField(
            model_name='reciclagem',
            name='tipo_residuo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciclagens', to='reciclagem.tiporesiduos'),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('semestre', models.IntegerField()),
                ('turno', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='reciclagem.curso')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
        migrations.DeleteModel(
            name='TipoResiduo',
        ),
    ]
