# Generated by Django 5.2 on 2025-04-24 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclagem', '0005_cidade_estado_tiporesiduos_remove_reciclagem_turno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cursos', to='reciclagem.unidade'),
        ),
        migrations.AlterField(
            model_name='reciclagem',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reciclagens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reciclagem',
            name='tipo_residuo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reciclagens', to='reciclagem.tiporesiduos'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='turmas', to='reciclagem.curso'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unidades', to='reciclagem.cidade'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unidades', to='reciclagem.estado'),
        ),
    ]
