# Generated by Django 5.2 on 2025-04-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciclagem', '0008_alunos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alunos',
            new_name='Aluno',
        ),
    ]
