# Generated by Django 5.2 on 2025-04-24 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclagem', '0009_rename_alunos_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciclagem',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reciclagens', to='reciclagem.aluno'),
        ),
    ]
